redis:
  addr: "localhost:6379"
  password: ""
  db: 0

mysql:
  student:
    name: "dyf"
    password: "123"
    addr: "localhost:3306"
    db: "student"
  teacher:
    name: "dyf"
    password: "123"
    addr: "localhost:3306"
    db: "teacher"